#!/usr/bin/env python3
"""
drills.py — Complete drill database, 110 drills across 8 categories.
Add new drills here only. No layout or diagram logic.
"""

CAT_COLORS = {
    "infield":     "#132448",
    "outfield":    "#1A6B3C",
    "throwing":    "#854F0B",
    "situational": "#534AB7",
    "baserunning": "#993556",
    "hitting":     "#B31B1B",
    "catching":    "#B8860B",
    "pitching":    "#0E7C7B",
}

DRILLS = {
    # INFIELD (14)
    1:{"name":"Short Hops","cat":"infield","game":False,"desc1":"Bounce short hops 8-10 ft, work glove angles and soft hands","desc2":"Focus on glove position and late squeeze timing","cues":["Get low early — don't wait for the hop","Glove out front, not tucked","Soft hands — squeeze late"]},
    2:{"name":"Rapid-Fire Grounders","cat":"infield","game":False,"desc1":"Coach fires rapid-fire grounders to 3 infield positions simultaneously","desc2":"Forces quick feet and transitions under pressure","cues":["Charge the ball — don't wait","Field at your left foot","Come up throwing — no pause"]},
    14:{"name":"Infield Triangle","cat":"infield","game":False,"desc1":"SS, 2B, 1B work base coverage and communication on steals and bunts","desc2":"Pre-pitch communication so everyone knows their assignment","cues":["Talk before the pitch — not during","SS: signal who has 2nd","Everyone has a job — no standing still"]},
    21:{"name":"Goalie","cat":"infield","game":True,"desc1":"Two gloves as goalposts 6 ft apart. Coach at 15 yds. Field clean or eliminated","desc2":"Stop-the-ball-first mentality in a competitive elimination format","cues":["Get low and stay wide","Stop the ball first — don't reach","Glove down, body behind it"]},
    24:{"name":"Belly Ups","cat":"infield","game":True,"desc1":"Players lie flat in infield. Coach hits grounder — get to feet and throw to 1st","desc2":"Explosive recovery and composure when compromised","cues":["Get to feet fast — don't crawl","Settle your feet before the throw","Strong throw — you're already compromised"]},
    25:{"name":"King of the Hill","cat":"infield","game":True,"desc1":"Coach hits grounders to ranked line. Error = move down. Clean play = hold or advance","desc2":"Field clean AND throw strong to hold the top spot","cues":["Attack the ball","Field it clean AND throw it strong","No easy reps at the front"]},
    26:{"name":"Scramble","cat":"infield","game":True,"desc1":"Field and throw 5 consecutive grounders to 1B as fast and accurately as possible","desc2":"Low-reset quick-feet reps under speed pressure","cues":["Stay low between reps","Quick feet — don't fully reset","Grip fast — don't fuss"]},
    32:{"name":"Pinball","cat":"infield","game":True,"desc1":"Coach hits grounders to ranked line. Errors move you down. Hold the top","desc2":"Pressure reps — embrace the competition or fall in the rankings","cues":["Attack the ball — don't wait","Glove work AND throw both count","Pressure makes you better — embrace it"]},
    64:{"name":"Charge and Go","cat":"infield","game":False,"desc1":"IF charges a ball placed just inside the basepath, fields it moving, and cocks the throw to first","desc2":"Builds the habit of attacking a slow roller instead of waiting on it","cues":["Circle the ball so momentum carries toward first","Glove down, back flat, eyes on the ball","Crossover into the throw"]},
    65:{"name":"Ready Hop","cat":"infield","game":False,"desc1":"IF times two short steps to the pitcher's delivery, landing as the ball is released","desc2":"Gets fielders moving before contact instead of standing flat-footed","cues":["Feet wide, weight forward, hands low","Second step lands right on release","Lean toward where the pitch is likely to go"]},
    66:{"name":"Bowling Ball","cat":"infield","game":False,"desc1":"Partner rolls grounders straight at, then randomly around, a fielder in the ready position","desc2":"Repetition builder for glove-out, soft-hands fielding","cues":["Glove out front, not tucked in","Watch it all the way into the glove","Funnel the ball to the belt before the throw"]},
    67:{"name":"Bare Hands Only","cat":"infield","game":False,"desc1":"Partners toss the ball back and forth catching barehanded, cushioning instead of squeezing","desc2":"Builds hand-eye coordination and soft hands without a glove to hide behind","cues":["Track one seam all the way in","Cushion it, don't clamp it","Step back after 5 clean catches in a row"]},
    68:{"name":"Glove Trap","cat":"infield","game":False,"desc1":"Partners toss the ball to be trapped between the back of the glove and the throwing hand","desc2":"Builds a second, more secure way to control a tough-hop ball","cues":["Trap it out in front of the body","Bring both hands to the midsection to cushion it","Step back every 5 clean reps"]},
    69:{"name":"Open the Pocket","cat":"infield","game":False,"desc1":"Partners toss the ball to be caught with the glove pocket open and ready to pull for a quick transfer","desc2":"Builds the catch-and-transfer speed second basemen and shortstops need on a double play","cues":["Palm up, catch it out in front","Pull it back to the midsection to cushion","Practice the quick pull into a throwing grip"]},

    # OUTFIELD (17)
    5:{"name":"Drop Step & Go","cat":"outfield","game":False,"desc1":"OFs read a ball going over their head. Drop-step and run to the spot","desc2":"Builds hip turn and angle-run mechanics for deep balls","cues":["Drop step first — never backpedal","Turn hips — run on angle","Get to the spot before the ball"]},
    6:{"name":"Do-or-Die","cat":"outfield","game":True,"desc1":"Ball rolled in front of OF. Runner on 3rd, 1 out. Charge, field on the run, throw home","desc2":"Game-speed decision making on the do-or-die play","cues":["Charge hard — never slow down","Field on throwing-side foot","Throw a line drive, not a rainbow"]},
    10:{"name":"First Step / Reaction","cat":"outfield","game":False,"desc1":"Coach hits without cue. OFs react with correct first step in 1-2 beats","desc2":"Pre-pitch stance and instant first-step read development","cues":["Weight on balls of feet","Crossover wide, drop step deep","React with feet, not eyes"]},
    16:{"name":"Fly Ball Communication","cat":"outfield","game":False,"desc1":"Two OFs chase the same ball. Call rules, back-off rules, priority system","desc2":"Builds voice habits and outfield priority understanding","cues":["Call it LOUD and early","CF beats corner OFs — always","Peel off when you hear the call"]},
    19:{"name":"Tennis Ball Reaction","cat":"outfield","game":True,"desc1":"Coach throws tennis balls from 15-20 ft without warning. React and catch","desc2":"Hand-eye and reaction speed in a low-stakes competitive format","cues":["Stay on your toes","Expect every ball","Hands out front"]},
    23:{"name":"Wide Receiver","cat":"outfield","game":True,"desc1":"OFs run downfield routes. Coach throws — track the ball over the shoulder","desc2":"Builds over-the-shoulder catch and route-running tracking skills","cues":["Run the route first — don't watch early","Turn your head at the spot","Eyes on ball all the way in"]},
    43:{"name":"Four-Outfield Alignment","cat":"outfield","game":True,"desc1":"Full 4-OF setup. Coach calls the situation and OFs set positioning as a unit before the ball is hit","desc2":"Emphasis on gap coverage, priority calls between LCF and RCF, and how alignment shifts by hitter type","cues":["LCF and RCF must negotiate the middle — CF no longer owns it","Call your zone before the pitch, not after contact","Scored: ball drops uncalled = offense point"]},
    44:{"name":"Shade & Depth","cat":"outfield","game":False,"desc1":"Coach calls a batter type and count. OFs adjust positioning before the pitch — no ball hit","desc2":"Pure pre-pitch IQ rep. Builds the habit of reading situations and moving before the ball is in play","cues":["Pull hitter: shade 10 steps toward the pull side","2-strike count: creep in two steps","Talk to each other — everyone adjusts together"]},
    55:{"name":"Footwork Ladder","cat":"outfield","game":False,"desc1":"OF catches a fly ball then fires 3 quick steps (catch-grip-throw) back to the coach","desc2":"Builds the habit of exploding into a throw right off the catch","cues":["Glove foot forward on the catch","Second step grips the ball","Throw off the back foot's momentum"]},
    56:{"name":"Fence Sprint","cat":"outfield","game":False,"desc1":"OF sprints from center toward the fence as the coach leads a ball ahead of him","desc2":"Forces a full-speed read and close on a ball hit toward the gap","cues":["Take the shortest angle, not a straight line","Sprint through the catch, don't glide","Set the feet before the throw"]},
    57:{"name":"180 Read","cat":"outfield","game":False,"desc1":"Coach hits a ball behind a sprinting OF, forcing a quick turn and re-locate","desc2":"Teaches the front pivot or reverse pivot for balls misjudged in flight","cues":["Pick one turn style and commit","Don't panic — find the ball fast","Recover speed immediately after the turn"]},
    58:{"name":"Blind Spot","cat":"outfield","game":False,"desc1":"OF starts facing the fence, looks back over the shoulder to track a ball hit deep","desc2":"Builds comfort tracking a ball without turning the whole body","cues":["Keep the head turned, not the hips","Find the ball early","Run through the catch point"]},
    59:{"name":"Get Up","cat":"outfield","game":False,"desc1":"OF starts on the ground, coach hits a fly ball on contact, player scrambles up to make the play","desc2":"Builds recovery instinct if a player slips or is caught out of position","cues":["Eyes up first, feet second","Don't fight to your feet — roll to them","Sprint the whole way, no half effort"]},
    60:{"name":"Over the Head","cat":"outfield","game":True,"desc1":"OF catches a soft fly ball with the glove tucked behind the back, straight overhead","desc2":"Sharpens footwork, glove control, and focus under an unusual catch angle","cues":["Track it dead overhead, don't turn sideways","Trust the glove position, don't peek","Soft balls with younger players"]},
    61:{"name":"Through the Legs","cat":"outfield","game":True,"desc1":"OF catches a soft fly ball with the glove threaded between the legs","desc2":"Same focus and glove-awareness benefit as the overhead catch, different angle","cues":["Bring the glove hand around from behind","Keep both feet flat for the harder version","Soft balls only until it's mastered"]},
    62:{"name":"Slide and Snag","cat":"outfield","game":False,"desc1":"OF charges a short fly ball and finishes with a bent-leg slide to make the catch","desc2":"Safe way to extend range on a ball at the edge of a fielder's reach","cues":["Slide on the rear end, not the side","Keep the straight leg slightly bent","Shoes off first rep to build confidence"]},
    63:{"name":"Change of Direction","cat":"outfield","game":False,"desc1":"Coach signals a direction, OF reacts with the matching crossover, drop step, or ground-and-pop","desc2":"Pure first-step reaction training, no ball involved","cues":["No false step before you move","Eyes stay on the coach","Chop the feet between signals"]},

    # THROWING (13)
    3:{"name":"4-Corner Relay","cat":"throwing","game":False,"desc1":"Ball moves around all four bases as fast as possible. Race the clock","desc2":"Emphasizes catch-and-turn efficiency at each base","cues":["Catch and turn in one motion","Step toward target","Strong crow hop before throwing"]},
    4:{"name":"Knockout","cat":"throwing","game":True,"desc1":"Players queue at the mound. One throw each to hit the target. Miss = eliminated","desc2":"Competitive pressure throwing — last player standing wins","cues":["Pick a spot on the target","Full effort every rep","Compete — no lazy throws"]},
    9:{"name":"Crow Hop Station","cat":"throwing","game":False,"desc1":"Isolated throwing mechanics. Gather-hop-throw pattern. Pairs, 40-50 ft","desc2":"Build proper weight transfer and hip lead before the throw","cues":["Gather weight on back foot","Short hop into the throw","Lead with hip — finish over front foot"]},
    15:{"name":"Bucket Challenge","cat":"throwing","game":True,"desc1":"Throw to hit a bucket from increasing distances. Win = advance to next distance","desc2":"Accuracy focus with competitive distance progression","cues":["Pick the bucket — aim small","Four-seam grip every throw","Accuracy over velocity"]},
    22:{"name":"Relay Race Throw","cat":"throwing","game":True,"desc1":"Two teams, lines 10 yds per player. Ball relays front to back. First done wins","desc2":"Speed and accuracy under team competition pressure","cues":["Pivot and turn in one motion","Strong accurate throw — not just fast","Catch and go — no pause"]},
    31:{"name":"Ultimate Baseball","cat":"throwing","game":True,"desc1":"Football-style: advance ball into endzone by throwing and catching only","desc2":"Move fast after catch — pivot only, drops turn it over","cues":["Find the open teammate","Catch with two hands — drops turn it over","Move fast after catch — pivot only"]},
    45:{"name":"Long Toss Ladder","cat":"throwing","game":True,"desc1":"Pairs start at 30ft and step back every 3 clean exchanges. Max distance at the end wins","desc2":"Builds arm strength and crow hop consistency under distance pressure over a full session","cues":["Crow hop every throw — no flat feet","Arc it slightly at distance — don't muscle it flat","3 clean in a row to step back, one bounce and you hold"]},
    46:{"name":"Accuracy Ladder","cat":"throwing","game":True,"desc1":"Two targets at 30, 45, and 60ft. Hit the target to advance. Miss and hold. Race your partner","desc2":"Competitive accuracy format — forces grip focus and follow-through at each distance","cues":["Pick a specific spot on the target — aim small","Four-seam grip every rep","Follow through to the target — don't pull off early"]},
    54:{"name":"Team Throw Relay Run","cat":"throwing","game":True,"desc1":"2 teams, 4-5 balls lined up 10 yds out. Player sprints, fields, turns and throws to a teammate who catches, drops it, and sprints for the next ball","desc2":"Speed and accuracy under fatigue — builds relay habits and competitive throwing mechanics","cues":["Catch before you celebrate","Turn and throw in one motion","Sprint the whole way, no jogging"]},
    70:{"name":"Grip Check","cat":"throwing","game":False,"desc1":"Players establish a four-seam grip before every catch, first with eyes open, then closed","desc2":"Builds the grip into muscle memory so it's automatic before any throw","cues":["Grip like an egg — a gap between ball and palm","Never fiddle with the grip mid-throw","Fingers across the horseshoe seam"]},
    71:{"name":"No Stride","cat":"throwing","game":False,"desc1":"Partners play catch with feet planted, no stride, to isolate hip and torso rotation","desc2":"Removes the legs so the power has to come from the trunk and arm path","cues":["Feet wider than shoulder width, toes at partner","Four-seam grip every time","Full extension despite no stride"]},
    72:{"name":"One Bounce","cat":"throwing","game":False,"desc1":"Partners play catch using one-hop throws aimed a third of the way to the target","desc2":"Builds the downhill arm angle and follow-through that carries into a stronger regular throw","cues":["Get on top of the ball at release","Finish across the front knee","Alternate one-hops with regular throws"]},
    73:{"name":"Called Shot","cat":"throwing","game":False,"desc1":"Partners at pitching distance call a body-part target (shoulder, hip, knee) before every throw","desc2":"Warmup drill that sharpens command instead of just loosening the arm","cues":["Four-seam grip on every throw","Receiver sets the glove at the target first","Smooth arm action, not a velocity drill"]},

    # SITUATIONAL (22)
    7:{"name":"Cutoff Relay","cat":"situational","game":False,"desc1":"Full relay: OF to cutoff to home. Communication and relay footwork emphasized","desc2":"Everyone must know their position in the relay chain","cues":["Cutoff: hands up, give OF a target","Square up fast — one motion","Call it — silence loses runs"]},
    8:{"name":"Double Play Footwork","cat":"situational","game":False,"desc1":"Teach the 2B pivot. Slow reps first, full speed second. SS and 2B alternate","desc2":"Bag contact, pivot efficiency, and getting off the bag","cues":["Get to the bag early","Touch the corner — not the top","Get off the bag as fast as you got on"]},
    11:{"name":"Rundown (Pickle)","cat":"situational","game":True,"desc1":"Fielders aim to get out in 1 throw. Runner tries to extend the rundown","desc2":"Teaches run-hard, throw-ahead discipline in rundown situations","cues":["Run hard at runner — make them commit","Throw ahead of runner","Never throw behind"]},
    18:{"name":"Bunt Coverage","cat":"situational","game":False,"desc1":"Everyone has a role. P charges, 3B reads, 1B covers 1st, 2B covers 2nd","desc2":"Full defensive assignment execution on bunt situations","cues":["P: off mound fast","Call the base before you throw","3B: read then decide"]},
    20:{"name":"Game Situation Gauntlet","cat":"situational","game":False,"desc1":"Coach announces scenario, hits ball, full defense reacts as a real game","desc2":"Debrief each play — understanding the why matters as much as execution","cues":["Know the situation before every pitch","Say the play out loud","Back up every throw"]},
    29:{"name":"Arizona","cat":"situational","game":True,"desc1":"3 teams: 1 bats, 2 play defense. Batter racks up total bases. Defense races to track","desc2":"Count total bases not just outs — keeps offense aggressive","cues":["Offense: run hard — pressure defense","Defense: communicate on contact","Count total bases not just outs"]},
    30:{"name":"Bunt-Off","cat":"situational","game":True,"desc1":"Team competition — best bunts by location. 3B line vs 1B line zones","desc2":"Directional bunt execution with zone scoring","cues":["Top half of the ball — no pop-ups","Angle the bat early","1B and 3B lines are different targets"]},
    33:{"name":"Steal Coverage","cat":"situational","game":False,"desc1":"Full-team live rep. Catcher throws, SS and 2B communicate coverage via signals","desc2":"Pitcher holds runner, 1B communicates, baserunners actually run. Rotate everyone through","cues":["Signal before the pitch — not after","One person calls it, other confirms","Catcher: hit your cutoff, not a lob"]},
    34:{"name":"First & Third Defense","cat":"situational","game":True,"desc1":"Offense on 1st and 3rd. Defense executes one of three reads: throw through, cut and fire home, or fake","desc2":"SS covers bag, 2B reads runner at 3rd. Score it — hardest play in youth baseball","cues":["SS: get to the bag early, no drift","2B: eyes on 3rd runner — communicate the read","Catcher: call the play before the pitch"]},
    37:{"name":"Cover Two Live","cat":"situational","game":True,"desc1":"Runner on 1st, coach hits grounder to SS or 2B side. They communicate who fields and who covers","desc2":"Runner tries to advance. Out = defense point, safe = offense point","cues":["Call it before the pitch — not during","SS fields right side, 2B fields left side default","No ball, get to the bag fast"]},
    38:{"name":"Cutoff Decision","cat":"situational","game":False,"desc1":"Full relay scenario with runner in motion. Cutoff reads: cut and fire home, let it go, or redirect","desc2":"Coach calls different base situations before each rep — decision reps are the whole point","cues":["Cutoff: hands up early, make yourself a target","Read the runner before you decide","Call your decision loud — no silent cuts"]},
    39:{"name":"Bunt Scramble","cat":"situational","game":True,"desc1":"Two teams. Offense bunts every pitch. Defense executes full coverage rotation","desc2":"Fair bunt safe = offense point, out = defense point, pop-up = defense gets two","cues":["Defense: assignments before pitch — always","P: off mound at first movement","Call the base before you field it"]},
    42:{"name":"Situation Sprint","cat":"situational","game":True,"desc1":"Coach calls scenario out loud: 'Runner on 2nd, single to right... GO.' No pre-setup","desc2":"Full team. Offense runs, defense rotates and executes the correct play. Score it live","cues":["Know your assignment before the ball lands","Talk — silence is the same as wrong","This is a test of every rep you've done all season"]},
    47:{"name":"Score From Second","cat":"situational","game":True,"desc1":"Runner on 2nd, single to the OF. Runner reads the hit and makes the turn-or-hold decision at 3rd","desc2":"Scored by team. Teaches the read at 3rd base coach and the decision to go or stop","cues":["Read the ball off the bat — don't wait for the hop","Round 3rd wide if you're going","If you stop at 3rd, stop hard — don't drift past the bag"]},
    48:{"name":"Backup Positioning","cat":"situational","game":False,"desc1":"Coach hits to various spots. Every player not fielding sprints to their correct backup position","desc2":"Coach freezes the play and checks positioning. Pure team IQ — teaches who backs up what","cues":["If you don't have the ball, you have a backup assignment","P backs up every throw to a base — always","Never watch the play standing still"]},
    49:{"name":"OF Cutoff Alignment","cat":"situational","game":False,"desc1":"Ball hit to left, center, or right. Cutoff man aligns himself between OF and the target base","desc2":"OF holds the ball until cutoff is properly set. Teaches the alignment piece most teams never practice","cues":["Cutoff: get in line between OF arm and the base","Hands up — give the OF a target to throw to","Read the throw early — cut or let it go, commit loud"]},
    53:{"name":"Soft Toss Situational","cat":"situational","game":True,"desc1":"4 infielders vs 4 hitters (5v5 with 1 in OF if you've got 10). Coach soft tosses, group scrimmages live situations","desc2":"Full competitive rep with real defensive assignments and baserunning reads on every play","cues":["Read the situation before the toss","Call the play out loud","Play it like a real at bat"]},
    74:{"name":"Loop It","cat":"situational","game":True,"desc1":"Full infield runs a continuous choreographed sequence of throws around the diamond","desc2":"Rotation speed and clean footwork under a live time limit","cues":["Call the sequence out loud until memorized","Already moving into the next throw as you catch","Count clean rotations in 30-60 seconds"]},
    75:{"name":"Who's Got It","cat":"situational","game":False,"desc1":"Slow roller hit between the mound and first, pitcher and first baseman decide on the fly who fields it and who covers","desc2":"Removes the most common youth-level communication breakdown at first base","cues":["Ball called first, Bag called second","First baseman is the captain on this one","Pitcher tags the bag with the right foot, stays inside the line"]},
    76:{"name":"Right Side Gap","cat":"situational","game":False,"desc1":"Ball hit in the 1B/2B gap, first and second baseman both go, pitcher covers first","desc2":"Teaches the pitcher's habit of always sprinting to cover first on anything to the right side","cues":["First baseman takes as much ground as he can","Second baseman fields anything not called","Pitcher covers every time, no exceptions"]},
    77:{"name":"Ring the Bag","cat":"situational","game":False,"desc1":"Ground ball to first baseman, shortstop covers second for the throw, then fires back to the pitcher covering first","desc2":"A double-play look that doesn't start with the middle infield, a common gap in youth defense","cues":["Shortstop sets up 8 steps off the bag with a runner on","Get within 3 feet of the bag before breaking down","Tag with the throwing-side foot, step and throw"]},
    78:{"name":"Overthrow Drill","cat":"situational","game":False,"desc1":"Pitcher intentionally overthrows a pickoff to second, shortstop lets it go and becomes the cutoff man, pitcher sprints to back up third","desc2":"Teaches backup and relay positioning on the one throw most teams never practice","cues":["Pitcher sprints hard to a spot 10-15 feet behind the base","Outfielder charges the overthrow, crow-hops the relay","Third baseman decides cutoff or let-through, out loud"]},

    # BASERUNNING (14)
    12:{"name":"Tag-Up Race","cat":"baserunning","game":True,"desc1":"Fly ball to OF, runner on 3rd tags up and races to score against live throw","desc2":"Foot contact, timing, and aggressive read off the catch","cues":["Foot on base — don't leave early","Sprint the moment they catch it","Always slide if it's close"]},
    13:{"name":"Leads & Reads","cat":"baserunning","game":False,"desc1":"Primary and secondary leads, reading the pitcher, post-pitch reactions","desc2":"Builds the habit of taking correct lead lengths by situation","cues":["2 steps primary lead","Shuffle 2 steps on pitch","Dirt ball: go — don't hesitate"]},
    27:{"name":"3-2-1 Run","cat":"baserunning","game":True,"desc1":"Runner races home to 2nd before 3B delivers 3 throws to 2nd","desc2":"First base corner mechanics and turn-and-go aggression","cues":["Hit 1B on the inside corner","Explode out of the turn","Head down all the way"]},
    28:{"name":"Doubles","cat":"baserunning","game":True,"desc1":"Batter tries to leg out a double while OF throws them out at 2nd","desc2":"Aggressive first-base turn and read into 2nd base","cues":["Round 1st aggressively","Head up approaching 2nd — read the throw","Slide hard"]},
    35:{"name":"First to Third","cat":"baserunning","game":True,"desc1":"Live OF reads. Coach hits ball to OF while runner on 1st reads the defender","desc2":"Rule taught: if OF moves more than one step laterally, runner goes to 3rd. Score by team","cues":["Read the outfielder, not the ball","One lateral step = you go","Round 2nd wide — don't cheat the turn"]},
    36:{"name":"Wild Pitch Advance","cat":"baserunning","game":True,"desc1":"Runner on 2nd or 3rd takes secondary lead as coach rolls a ball past the catcher","desc2":"Team scores for advances, catcher scores for runners held or thrown out","cues":["Secondary lead timing is everything","React before the ball stops rolling","Slide — never assume you're safe"]},
    50:{"name":"Dirt Ball Read","cat":"baserunning","game":True,"desc1":"Runner on 3rd, 3-2 count, full go. Coach bounces pitch in the dirt. Runner reads and goes or holds","desc2":"Catcher scored for blocks and throws, runner scored for clean advances","cues":["Go on contact with the dirt — don't wait to see the block","If catcher blocks it clean and close, slam the brakes","Never get thrown out at home on a dirt ball — make them earn it"]},
    51:{"name":"Gap Shot","cat":"baserunning","game":True,"desc1":"Ball hit to the gap with runner on 1st. Runner reads the hit, rounds 2nd aggressively, decides at 3rd","desc2":"Full OF plays out live. Scored: runner scores = offense point, thrown out = defense point","cues":["Read gap off the bat — go immediately, don't hesitate","Round 2nd at full speed, look up at 3rd coach coming into the bag","Aggressive default: when in doubt, keep running"]},
    79:{"name":"Form Circuit","cat":"baserunning","game":False,"desc1":"Rotating warmup through high knees, buttkickers, grapevines, bounding, and backward running","desc2":"Builds running mechanics generally, before any baseball-specific baserunning work","cues":["Quality of form over speed on every rep","Arms drive opposite the legs","Backward running: push off the forefoot, use the core"]},
    80:{"name":"Shuffle and Go","cat":"baserunning","game":False,"desc1":"Runner takes a lead-off stance, shuffles out, then crosses over into a full sprint on the signal","desc2":"Builds a safe, balanced lead that can still dive back if needed","cues":["Small shuffle steps, never a big crossover early","No false step with the back foot","Stay low the first 3-4 steps off the break"]},
    81:{"name":"Shoulder Turn","cat":"baserunning","game":False,"desc1":"Runner sprints, then turns the shoulders and whips the arm across the body to change direction toward the next base","desc2":"Builds the mechanic that makes a base-to-base turn fast instead of a wide loop","cues":["Keep pumping the arms through the turn","Don't let the turn break your rhythm","Exaggerate it in practice until natural"]},
    82:{"name":"Square the Bases","cat":"baserunning","game":False,"desc1":"Four groups practice turns at each base in sequence, walk through first, then building to full speed","desc2":"Full basepath rehearsal from a standing start to game speed","cues":["Tag the inside corner with the left foot","Cut each base on the sharpest angle you can","Don't skip a speed phase — walk, jog, 3/4, full"]},
    83:{"name":"Extra Base","cat":"baserunning","game":True,"desc1":"Runner sprints to first, makes an aggressive turn toward second, and breaks down at a cone to read the throw","desc2":"Trains runners to turn singles into doubles on a slow outfield throw","cues":["Run through first like you're not stopping","Break down low, feet moving, head on a swivel","Decide to advance or retreat, don't drift"]},
    84:{"name":"Bent Leg","cat":"baserunning","game":False,"desc1":"Runner practices the bent-leg slide first from a seated start, then running in at speed into a base","desc2":"Safe standard slide technique, less injury risk than a headfirst dive","cues":["Slide on the rear end, not the side","Straight leg stays slightly bent, never locked","Go in fast — slowing down increases injury risk"]},

    # HITTING (11)
    17:{"name":"Soft Toss","cat":"hitting","game":False,"desc1":"Partner feeds from 45 degree angle. Load, hip turn, contact point. High-rep","desc2":"Reinforce load timing and hip rotation through the zone","cues":["Load before toss arrives","Short to ball, long through it","Stay back — don't lunge"]},
    40:{"name":"Oppo Tee Challenge","cat":"hitting","game":True,"desc1":"Outside tee placement, ball set deep in the zone. Hit 3 consecutive balls to the opposite field","desc2":"One point per clean oppo hit — pull it foul and you're out of rotation","cues":["Let the ball get deep — don't reach","Stay through the ball to the opposite gap","Hands inside, barrel outside"]},
    41:{"name":"Two-Tee Location Game","cat":"hitting","game":True,"desc1":"Two tees set inside and outside. Coach calls the location, hitter adjusts and hits correct tee","desc2":"Wrong tee = out of rotation. Builds plate coverage and pitch recognition in the box","cues":["React to the call — not the guess","Inside: pull angle, Outside: oppo angle","Adjust your feet, not just your hands"]},
    52:{"name":"Front Toss Battle","cat":"hitting","game":True,"desc1":"Two hitters compete head to head, coach front-tossing 5 pitches each. Scored by zone","desc2":"Oppo = 2pts, up the middle = 1pt, pull = 0. Forces intentional hitting under real competition pressure","cues":["Pick your zone before the toss — commit to it","Stay back and let the ball travel to your spot","Oppo isn't weak — it's disciplined"]},
    85:{"name":"No Ball Reps","cat":"hitting","game":False,"desc1":"Hitters walk through relax-ready-stride-swing phase by phase, adjusting hips and hands for pitch location","desc2":"Isolates the swing sequence without a ball to worry about","cues":["Walk away from the hands on the stride","Back hip always points to the target","Stride to the same spot no matter the pitch location"]},
    86:{"name":"Whoosh Check","cat":"hitting","game":False,"desc1":"Hitter swings a dowel and listens for the whoosh to land in the direction of the intended pitch location","desc2":"Instant audio feedback on swing path, doable at home with no ball","cues":["Whoosh to the opposite field on an outside pitch","Whoosh to center on a middle pitch","5-10 reps per pitch location"]},
    87:{"name":"Bag Work","cat":"hitting","game":False,"desc1":"Hitter makes contact into a hanging punching bag, moving forward or back to work different pitch locations","desc2":"Live-contact feel without the unpredictability of a live pitch","cues":["Move forward for outside, back for inside","Bottom hand palm down at contact","5-10 swings per location"]},
    88:{"name":"Tee Zones","cat":"hitting","game":False,"desc1":"Hitter works the tee at three depths (middle, back for outside, front for inside) for 5-10 swings each","desc2":"Trains contact point to shift with pitch location instead of a one-size swing","cues":["Square stance regardless of pitch location","Open or close the hips, not the stance","Separate the stride from the swing"]},
    89:{"name":"Two Ball Toss","cat":"hitting","game":False,"desc1":"Coach cues the stride with one hand, then soft tosses with the other, exaggerating the gap between stride and swing","desc2":"Breaks a hitter of swinging and striding as one rushed motion","cues":["Stride on the first hand cue, wait for the toss","Speed the sequence up as it clicks","25 reps per session"]},
    90:{"name":"Pepper","cat":"hitting","game":True,"desc1":"Hitter taps grounders to a line of 3 fielders 20 feet away, a fielding error sends that player to the back of the line","desc2":"Fast-paced hand-eye and fielding reps in one small-space game","cues":["Choke up, short compact swing","Foul ball or swing-and-miss retires the batter","Play to 20 points for a competitive version"]},
    91:{"name":"Gap Targets","cat":"hitting","game":False,"desc1":"Hitter aims soft-toss pitches through cone gaps set for pull, center, and opposite field","desc2":"Connects pitch location directly to where the ball should actually go","cues":["Hit the back half of a middle pitch","Hit the inside half of an outside pitch","Hit the outside half of an inside pitch"]},

    # CATCHING (7)
    92:{"name":"Set Position","cat":"catching","game":False,"desc1":"Catchers build the stance from the ground up: athletic base, elbows to knees, toes out, gradually lowering","desc2":"Foundation stance work before any receiving or blocking drills","cues":["Feet wider than shoulder width","Knees stay inside the feet","Lower gradually until comfortable, not forced"]},
    93:{"name":"Step and Stay Down","cat":"catching","game":False,"desc1":"Catcher stays down in the stance and takes a short controlled step to a pitch thrown or pointed left or right","desc2":"Trains lateral movement without popping up out of the crouch","cues":["Head stays level side to side","Slightly more weight on the glove-side foot","Step with the outside foot, not a lunge"]},
    94:{"name":"Grip and Rise","cat":"catching","game":False,"desc1":"Catcher catches, rises, and steps into a throwing grip in one fluid motion before freezing to check the grip","desc2":"Builds the catch-to-throw speed a catcher needs on a stolen base","cues":["Four-seam grip every time","Never fiddle with the grip on the cock-back","One fluid motion, not three separate steps"]},
    95:{"name":"In the Dirt","cat":"catching","game":False,"desc1":"Coach tosses balls into the dirt, catcher drops to block with knees, mitt, and body angled forward","desc2":"Core blocking technique to keep any pitch in the dirt in front of the catcher","cues":["First move is down, not up","Mitt drops between the legs, web on the ground","Angle the upper body forward over the ball"]},
    96:{"name":"Live Blocks","cat":"catching","game":False,"desc1":"Pitcher intentionally throws balls in the dirt during a live bullpen, catcher blocks every one","desc2":"The one blocking rep that finally happens off a real pitcher instead of a coach's soft toss","cues":["Feet wide, heels down, thighs parallel before the pitch","First move is down into the knees, not up","Squeeze the elbows in for one big blocking surface"]},
    97:{"name":"Pounce","cat":"catching","game":False,"desc1":"Catcher springs from the stance to field a simulated bunt and throw to first","desc2":"Reaction speed off the bunt, the catcher's most common bang-bang play","cues":["Pick the ball up with both hands","Line up the feet to first as you field it","Sprint under control, don't lunge"]},
    98:{"name":"Find It","cat":"catching","game":False,"desc1":"Pitcher throws balls in the dirt on purpose and calls out where the loose ball ends up (front, back, first, third)","desc2":"Builds the verbal habit that saves a split second on a run-scoring play","cues":["Ball is called first, then a location","Scoop with both hands, find the grip fast","Shout it — this is not a quiet play"]},

    # PITCHING (12)
    99:{"name":"Pivot Hold","cat":"pitching","game":False,"desc1":"Pitcher rockers into the pivot, then holds the balance position with the stride leg up for a five count","desc2":"Foundational balance work before any actual pitch is thrown","cues":["Weight stays on the inside of the pivot foot","Pivot foot stays planted, no shuffling","Stride toe hangs loose, slightly below the heel"]},
    100:{"name":"Stride Hold","cat":"pitching","game":False,"desc1":"Pitcher goes through the full delivery, then holds balance on the stride foot alone after a simulated release","desc2":"Tests balance and control at the exact moment most deliveries fall apart","cues":["Form the T-position at foot strike","Head moves directly over the stride leg","Hold for a full five count"]},
    101:{"name":"Pivot Hops","cat":"pitching","game":False,"desc1":"Pitcher hops three times on the pivot foot after reaching the balance position, then freezes","desc2":"Adds a dynamic balance challenge on top of the static hold","cues":["Small hops, 4-6 inches","Weight stays inside the pivot foot","Freeze clean after the third hop"]},
    102:{"name":"Stride Hops","cat":"pitching","game":False,"desc1":"Pitcher completes the delivery, then hops three times on the stride foot before holding for a count","desc2":"Combine with Pivot Hops once mastered for a full balance sequence","cues":["Same small hop size as the pivot version","Stay tall, don't collapse the landing leg","Hold the final position for a five count"]},
    103:{"name":"Eyes Shut","cat":"pitching","game":False,"desc1":"All four balance drills repeated with the eyes closed for an added difficulty layer","desc2":"Only introduce once the sighted version is solid","cues":["Same cues as the sighted versions","Slow down if balance is lost, don't rush","Try an uneven surface once this is easy"]},
    104:{"name":"Phase by Phase","cat":"pitching","game":False,"desc1":"Pitcher walks the full delivery one phase at a time (stance, pivot, stride, release), coach corrects between each","desc2":"The core teaching tool for building or rebuilding a pitcher's mechanics","cues":["Don't move on until the current phase is clean","Firm back leg, no drop-and-drive","Elbow at or above shoulder height going forward"]},
    105:{"name":"Snap Stick","cat":"pitching","game":False,"desc1":"Pitcher throws with a light dowel instead of a ball, listening for where the loudest whip sound happens","desc2":"Instant feedback on release point and arm speed","cues":["Sound should snap near the glove-side eye","Louder snap means more arm speed","10-15 reps per session"]},
    106:{"name":"Towel Snap","cat":"pitching","game":False,"desc1":"Pitcher throws a knotted towel at a glove held at the release point, aiming to snap it onto the target","desc2":"Builds extension and reinforces a consistent release point","cues":["Reach with the chest and head, not an over-stride","Stride stays aimed straight at the plate","Extend the arm fully toward the target"]},
    107:{"name":"Heel Roll","cat":"pitching","game":False,"desc1":"From a stationary T-position, pitcher slowly brings the arm through release while the pivot foot heel lifts and rotates out","desc2":"Isolates the back-foot mechanics of the follow-through","cues":["Toe stays planted, heel lifts and rotates","Stay balanced, don't rush the motion","Reach forward with the chest and head"]},
    108:{"name":"Over the Cup","cat":"pitching","game":False,"desc1":"Pitcher simulates the release, then lifts the back foot up and over a cup placed inside the stride foot","desc2":"Teaches the full weight transfer from pivot foot to stride foot","cues":["Circle over the cup, don't kick it","Finish with the pivot toe down, heel out","This completes the weight transfer — don't skip it"]},
    109:{"name":"Bottom and Up","cat":"pitching","game":False,"desc1":"From a stride position, pitcher drops the hands to bottom out, then separates into the T-position and throws","desc2":"Times the hand separation so the throwing arm gets up early enough","cues":["Thumbs down on the separation","Pull the glove arm into the hip for power","Release the ball on a downward plane"]},
    110:{"name":"Mound Bounce","cat":"pitching","game":False,"desc1":"Pitcher throws from the stride position, trying to one-hop the ball just in front of a cone two-thirds of the way to the target","desc2":"Combines arm separation, release point, and downhill plane in one throw","cues":["Fingers stay on top of the ball","Wrist stays straight and firm","Circle the pivot foot around to finish on the toe"]},
}

if __name__ == "__main__":
    from collections import Counter
    print(f"{len(DRILLS)} total drills")
    print(Counter(d["cat"] for d in DRILLS.values()))
